volumes:
  logs:
    driver: local
  db:
    driver: local

services:
  wordy-api:
    build: ./docker
    container_name: wordy-api
    environment:
      docker: "true"
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - logs:/var/www/logs
